### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by ItTakesTwo** [ewhal/Pastebin#4]
Make pulls [ChannelMeter/iso8601duration](https://github.com/ewhal/Pastebin/blob/master/Makefile#L16) but [pastebin.go](https://github.com/ewhal/Pastebin/blob/master/pastebin.go#L19) tries to import it from channelmeter/iso8601duration. Because of the capital letters in the file path, make fails to build.

**Comment by ewhal** [comment]
Should be solved.
